### ISSUE TITLE
Compatibility with drf-yasg

### ISSUE THREAD

**Issue by q0w** [dabapps/django-readers#70]
`ProjectionSerializer` does not have a `label` attribute, so drf-yasg fails:
```python
AttributeError: 'ProjectionSerializer' object has no attribute 'label'
```

**Comment by j4mie** [comment]
Hi,

I don't think this is going to be an easy fix, because the `ProjectionSerializer` doesn't know anything at all about what it's serializing. We might be able to silence the error, but even if we did the schema would be empty/meaningless.

I'm currently thinking about how django-readers might work with schemas. It's not simple because we (deliberately) don't consider types in our specs currently, and because of the way the library is designed we can't statically introspect the types from the underlying models easily. This will be a long-term piece of work I imagine, but I'll leave this issue open for now just so we can track it.

Thanks!

**Comment by j4mie** [comment]
#76 should give you everything you need to make this work 🎉 closing for now, please let me know if you have any issues.
